[2024-06-05 18:18:43,938] ERROR (创建解析任务和存储任务和中台任务.py:41) Invalid URL 'None/jax/api/v1/pipeline/jax_ECMP_TRACELOG_sq/stage': No scheme supplied. Perhaps you meant https://None/jax/api/v1/pipeline/jax_ECMP_TRACELOG_sq/stage?
Traceback (most recent call last):
  File "e:/Deskop/People/script/python/script/Aiops/创建解析任务和存储任务和中台任务.py", line 37, in do_request
    res = requests.request(method, url=url, headers=headers, json=payload)
  File "C:\Users\Farben\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Farben\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "C:\Users\Farben\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 486, in prepare_request
    p.prepare(
  File "C:\Users\Farben\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Farben\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None/jax/api/v1/pipeline/jax_ECMP_TRACELOG_sq/stage': No scheme supplied. Perhaps you meant https://None/jax/api/v1/pipeline/jax_ECMP_TRACELOG_sq/stage?
[2024-06-05 18:21:44,777] ERROR (创建解析任务和存储任务和中台任务.py:41) Invalid URL 'None/jax/api/v1/pipeline/jax_ECMP_TRACELOG_sq/stage': No scheme supplied. Perhaps you meant https://None/jax/api/v1/pipeline/jax_ECMP_TRACELOG_sq/stage?
Traceback (most recent call last):
  File "e:/Deskop/People/script/python/script/Aiops/创建解析任务和存储任务和中台任务.py", line 37, in do_request
    res = requests.request(method, url=url, headers=headers, json=payload)
  File "C:\Users\Farben\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Farben\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "C:\Users\Farben\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 486, in prepare_request
    p.prepare(
  File "C:\Users\Farben\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Farben\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None/jax/api/v1/pipeline/jax_ECMP_TRACELOG_sq/stage': No scheme supplied. Perhaps you meant https://None/jax/api/v1/pipeline/jax_ECMP_TRACELOG_sq/stage?
[2024-06-05 18:22:08,565] DEBUG (connectionpool.py:244) Starting new HTTP connection (1): 10.251.52.102:18080
[2024-06-05 18:22:08,613] DEBUG (connectionpool.py:546) http://10.251.52.102:18080 "POST /jax/api/v1/pipeline/jax_ECMP_TRACELOG_sq/stage HTTP/1.1" 200 None
[2024-06-05 18:22:08,615] INFO (创建解析任务和存储任务和中台任务.py:300) 创建jax_ECMP_TRACELOG_sq中台任务成功：成功
[2024-06-05 18:22:08,616] DEBUG (connectionpool.py:244) Starting new HTTP connection (1): 10.251.52.102:18080
[2024-06-05 18:22:11,741] DEBUG (connectionpool.py:546) http://10.251.52.102:18080 "POST /logAnalysis/api/itoa/dataset/stream HTTP/1.1" 200 None
[2024-06-05 18:22:11,750] ERROR (创建解析任务和存储任务和中台任务.py:194) 创建['APP_ECMP_TRACELOG_ETL']解析任务执行失败：无法获取[kafka]类型的中心地址，请检查后重试！
[2024-06-05 19:05:57,776] DEBUG (connectionpool.py:244) Starting new HTTP connection (1): 10.251.52.102:18080
[2024-06-05 19:05:57,812] DEBUG (connectionpool.py:546) http://10.251.52.102:18080 "POST /jax/api/v1/pipeline/jax_ECMP_TRACELOG_sq/stage HTTP/1.1" 200 None
[2024-06-05 19:05:57,813] INFO (创建解析任务和存储任务和中台任务.py:342) 创建jax_ECMP_TRACELOG_sq中台任务成功：成功
[2024-06-05 19:05:57,815] DEBUG (connectionpool.py:244) Starting new HTTP connection (1): 10.251.52.102:18080
[2024-06-05 19:05:57,935] DEBUG (connectionpool.py:546) http://10.251.52.102:18080 "POST /logAnalysis/api/itoa/dataset/stream HTTP/1.1" 200 None
[2024-06-05 19:05:57,942] INFO (创建解析任务和存储任务和中台任务.py:233) 创建['APP_ECMP_TRACELOG_ETL']解析任务成功：success, task_id:302507442880512
[2024-06-05 19:05:57,943] DEBUG (connectionpool.py:244) Starting new HTTP connection (1): 10.251.52.102:18080
[2024-06-05 19:06:02,123] DEBUG (connectionpool.py:546) http://10.251.52.102:18080 "POST /logAnalysis/api/itoa/dataset/storageOutPut HTTP/1.1" 200 None
[2024-06-05 19:06:02,126] INFO (创建解析任务和存储任务和中台任务.py:98) 创建['APP_ECMP_TRACELOG_ETL']存储任务成功：添加成功
[2024-06-05 19:06:02,128] DEBUG (connectionpool.py:244) Starting new HTTP connection (1): 10.251.52.102:18080
[2024-06-05 19:06:02,209] DEBUG (connectionpool.py:546) http://10.251.52.102:18080 "POST /jax/api/v1/pipeline/jax_ECMP_TRACELOG_zj/stage HTTP/1.1" 200 None
[2024-06-05 19:06:02,211] INFO (创建解析任务和存储任务和中台任务.py:342) 创建jax_ECMP_TRACELOG_zj中台任务成功：成功
[2024-06-05 19:06:02,213] DEBUG (connectionpool.py:244) Starting new HTTP connection (1): 10.251.52.102:18080
[2024-06-05 19:06:02,328] DEBUG (connectionpool.py:546) http://10.251.52.102:18080 "POST /logAnalysis/api/itoa/dataset/stream HTTP/1.1" 200 None
[2024-06-05 19:06:02,329] INFO (创建解析任务和存储任务和中台任务.py:233) 创建['APP_ECMP_TRACELOG_ETL']解析任务成功：success, task_id:302507460763648
[2024-06-05 19:06:02,331] DEBUG (connectionpool.py:244) Starting new HTTP connection (1): 10.251.52.102:18080
[2024-06-05 19:06:02,355] DEBUG (connectionpool.py:546) http://10.251.52.102:18080 "POST /logAnalysis/api/itoa/dataset/storageOutPut HTTP/1.1" 200 None
[2024-06-05 19:06:02,356] ERROR (创建解析任务和存储任务和中台任务.py:100) 创建['APP_ECMP_TRACELOG_ETL']存储任务成功：此索引标识已经存在，请重新填写！
[2024-06-05 19:09:28,780] DEBUG (connectionpool.py:244) Starting new HTTP connection (1): 10.251.52.102:18080
[2024-06-05 19:09:28,900] DEBUG (connectionpool.py:546) http://10.251.52.102:18080 "POST /logAnalysis/api/itoa/dataset/stream HTTP/1.1" 200 None
[2024-06-05 19:09:28,903] INFO (创建解析任务和存储任务和中台任务.py:233) 创建['APP_ECMP_TRACELOG_ETL']解析任务成功：success, task_id:302508306837504
[2024-06-05 19:09:28,904] DEBUG (connectionpool.py:244) Starting new HTTP connection (1): 10.251.52.102:18080
[2024-06-05 19:09:37,258] DEBUG (connectionpool.py:546) http://10.251.52.102:18080 "POST /logAnalysis/api/itoa/dataset/storageOutPut HTTP/1.1" 200 None
[2024-06-05 19:09:37,260] INFO (创建解析任务和存储任务和中台任务.py:98) 创建['APP_ECMP_TRACELOG_ETL']存储任务成功：添加成功
[2024-06-05 19:09:37,261] DEBUG (connectionpool.py:244) Starting new HTTP connection (1): 10.251.52.102:18080
[2024-06-05 19:09:37,398] DEBUG (connectionpool.py:546) http://10.251.52.102:18080 "POST /logAnalysis/api/itoa/dataset/stream HTTP/1.1" 200 None
[2024-06-05 19:09:37,401] INFO (创建解析任务和存储任务和中台任务.py:233) 创建['APP_ECMP_TRACELOG_ETL']解析任务成功：success, task_id:302508341796864
[2024-06-05 19:09:37,402] DEBUG (connectionpool.py:244) Starting new HTTP connection (1): 10.251.52.102:18080
[2024-06-05 19:09:40,458] DEBUG (connectionpool.py:546) http://10.251.52.102:18080 "POST /logAnalysis/api/itoa/dataset/storageOutPut HTTP/1.1" 200 None
[2024-06-05 19:09:40,459] INFO (创建解析任务和存储任务和中台任务.py:98) 创建['APP_ECMP_TRACELOG_ETL']存储任务成功：添加成功
[2024-06-05 19:16:55,130] DEBUG (connectionpool.py:244) Starting new HTTP connection (1): 10.251.52.102:18080
[2024-06-05 19:16:55,231] DEBUG (connectionpool.py:546) http://10.251.52.102:18080 "POST /logAnalysis/api/itoa/dataset/stream HTTP/1.1" 200 None
[2024-06-05 19:16:55,233] INFO (创建解析任务和存储任务和中台任务.py:233) 创建['APP_ECMP_TRACELOG_ETL']解析任务成功：success, task_id:302510135029760
[2024-06-05 19:16:55,234] DEBUG (connectionpool.py:244) Starting new HTTP connection (1): 10.251.52.102:18080
[2024-06-05 19:17:02,915] DEBUG (connectionpool.py:546) http://10.251.52.102:18080 "POST /logAnalysis/api/itoa/dataset/storageOutPut HTTP/1.1" 200 None
[2024-06-05 19:17:02,916] INFO (创建解析任务和存储任务和中台任务.py:98) 创建['APP_ECMP_TRACELOG_ETL']存储任务成功：添加成功
[2024-06-05 19:17:02,918] DEBUG (connectionpool.py:244) Starting new HTTP connection (1): 10.251.52.102:18080
[2024-06-05 19:17:02,992] DEBUG (connectionpool.py:546) http://10.251.52.102:18080 "POST /logAnalysis/api/itoa/dataset/stream HTTP/1.1" 200 None
[2024-06-05 19:17:02,995] INFO (创建解析任务和存储任务和中台任务.py:233) 创建['APP_ECMP_TRACELOG_ETL']解析任务成功：success, task_id:302510166941696
[2024-06-05 19:17:02,996] DEBUG (connectionpool.py:244) Starting new HTTP connection (1): 10.251.52.102:18080
[2024-06-05 19:17:06,628] DEBUG (connectionpool.py:546) http://10.251.52.102:18080 "POST /logAnalysis/api/itoa/dataset/storageOutPut HTTP/1.1" 200 None
[2024-06-05 19:17:06,628] INFO (创建解析任务和存储任务和中台任务.py:98) 创建['APP_ECMP_TRACELOG_ETL']存储任务成功：添加成功
